# run_daily.py
"""
生成 A 股日报（极简版）：
- 优先用 TuShare 拉取上证指数(000001.SH)最近一个交易日的日线
- 失败或无 Token 时自动降级到 AKShare
- 输出到 data/reports/report_YYYYMMDD.csv
"""
from __future__ import annotations
import os
import sys
import pathlib
from datetime import datetime, timezone, timedelta

import pandas as pd

# -------- 工具函数 --------
def today_cn_date_str() -> str:
    """北京时间的 yyyyMMdd 字符串。"""
    # 不额外依赖 pytz，手算东八区
    return (datetime.utcnow() + timedelta(hours=8)).strftime("%Y%m%d")

def ensure_dir(p: str | pathlib.Path) -> None:
    pathlib.Path(p).mkdir(parents=True, exist_ok=True)

def last_trade_day_tushare(pro) -> str:
    """用 TuShare 交易日历找 <= 今天的最近交易日（yyyyMMdd）。"""
    today = today_cn_date_str()
    cal = pro.trade_cal(exchange="SSE", start_date="20200101", end_date=today)
    cal = cal[cal["is_open"] == 1]
    return cal["cal_date"].max()

# -------- 主逻辑 --------
def fetch_with_tushare() -> pd.DataFrame:
    token = os.getenv("TUSHARE_TOKEN")
    if not token:
        raise RuntimeError("No TUSHARE_TOKEN in env")

    import tushare as ts
    ts.set_token(token)
    pro = ts.pro_api()

    trade_day = last_trade_day_tushare(pro)
    # 上证综指 ts_code 固定为 000001.SH
    df = pro.index_daily(ts_code="000001.SH", start_date=trade_day, end_date=trade_day)
    if df.empty:
        raise RuntimeError(f"TuShare index_daily empty for {trade_day}")

    # 统一字段
    df = df.rename(
        columns={
            "ts_code": "code",
            "trade_date": "date",
            "open": "open",
            "high": "high",
            "low": "low",
            "close": "close",
            "vol": "volume",
            "amount": "amount",
        }
    )
    # TuShare 的 date 是 yyyymmdd 字符串
    df["date"] = pd.to_datetime(df["date"], format="%Y%m%d")
    df["source"] = "tushare"
    return df[["date", "code", "open", "high", "low", "close", "volume", "amount", "source"]]

def fetch_with_akshare() -> pd.DataFrame:
    import akshare as ak

    # AKShare 指数代码：上证指数是 sh000001
    df = ak.index_zh_a_hist(symbol="sh000001", period="daily")
    # 字段中文 → 英文
    df = df.rename(
        columns={
            "日期": "date",
            "开盘": "open",
            "最高": "high",
            "最低": "low",
            "收盘": "close",
            "成交量": "volume",
            "成交额": "amount",
        }
    )
    df["date"] = pd.to_datetime(df["date"])
    # 取最近一行
    df = df.sort_values("date").tail(1).copy()
    df["code"] = "000001.SH"
    df["source"] = "akshare"
    return df[["date", "code", "open", "high", "low", "close", "volume", "amount", "source"]]

def main():
    out_dir = pathlib.Path("data/reports")
    ensure_dir(out_dir)

    # 先 TuShare，失败再 AKShare
    try:
        df = fetch_with_tushare()
        used = "TuShare"
    except Exception as e:
        print(f"[warn] TuShare failed: {e}", file=sys.stderr)
        df = fetch_with_akshare()
        used = "AKShare"

    # 输出文件名用北京时间
    stamp = (datetime.utcnow() + timedelta(hours=8)).strftime("%Y%m%d")
    out_path = out_dir / f"report_{stamp}.csv"
    df.to_csv(out_path, index=False, encoding="utf-8-sig")

    # 终端友好打印
    print(f"[ok] Daily report generated by {used}: {out_path}")
    print(df.to_string(index=False))

if __name__ == "__main__":
    main()
