name: daily-a-share-report

on:
  workflow_dispatch:            # 手动按钮
  schedule:
    - cron: "10 7 * * 1-5"      # UTC 07:10 == 北京时间 15:10，工作日

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: python run_daily.py

      - name: Commit daily report
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/reports/*.csv || true
          git commit -m "daily report $(date +'%F')" || echo "nothing to commit"
          git push
